export const ErrorCode = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_LOCKED: 'AUTH_LOCKED',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION: 'VALIDATION',
  POLICY: 'POLICY',
  RATE_LIMITED: 'RATE_LIMITED',
  SHARE_UNAVAILABLE: 'SHARE_UNAVAILABLE',
  SHARE_LOCKED: 'SHARE_LOCKED',
  OTP_INVALID: 'OTP_INVALID',
  TAMPER_DETECTED: 'TAMPER_DETECTED',
  CRYPTO_FAILURE: 'CRYPTO_FAILURE',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export const ErrorHttpStatus: Record<ErrorCode, number> = {
  AUTH_REQUIRED: 401,
  AUTH_LOCKED: 423,
  NOT_FOUND: 404,
  VALIDATION: 400,
  POLICY: 422,
  RATE_LIMITED: 429,
  SHARE_UNAVAILABLE: 404,
  SHARE_LOCKED: 423,
  OTP_INVALID: 400,
  TAMPER_DETECTED: 500,
  CRYPTO_FAILURE: 500,
};
